# Generated by Django 4.2.11 on 2024-03-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='用户ID')),
                ('age', models.CharField(max_length=10, verbose_name='年龄')),
                ('height', models.CharField(max_length=10, verbose_name='身高')),
                ('weight', models.CharField(max_length=10, verbose_name='体重')),
                ('avatarURL', models.ImageField(upload_to='images/avatar/', verbose_name='头像')),
                ('city', models.CharField(max_length=10, verbose_name='城市')),
                ('education', models.CharField(max_length=10, verbose_name='教育')),
                ('gender', models.SmallIntegerField(verbose_name='性别')),
                ('marriage', models.CharField(max_length=10, verbose_name='婚否')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('objectID', models.IntegerField()),
                ('jobs_title', models.CharField(max_length=10, verbose_name='职业')),
                ('online', models.IntegerField()),
                ('city_name', models.CharField(max_length=10, verbose_name='城市名')),
                ('hometown_name', models.CharField(max_length=10, verbose_name='家乡')),
                ('flagList', models.JSONField()),
                ('isvip', models.SmallIntegerField()),
                ('iscard', models.SmallIntegerField()),
                ('f_text', models.CharField(max_length=200)),
                ('updatetime', models.DateTimeField()),
                ('infoStatus', models.CharField(max_length=50)),
                ('placedtop', models.SmallIntegerField()),
                ('revenue', models.CharField(max_length=20, verbose_name='收入')),
                ('ismeet', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': '会员信息',
                'verbose_name_plural': '会员信息',
            },
        ),
        migrations.CreateModel(
            name='UsersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('showValidateIDCardFlag', models.SmallIntegerField(default=0)),
                ('workCityString', models.CharField(max_length=50, verbose_name='工作城市')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField()),
                ('isedu', models.SmallIntegerField()),
                ('iscar', models.SmallIntegerField()),
                ('ishouse', models.SmallIntegerField()),
                ('isvip', models.SmallIntegerField()),
                ('iscard', models.SmallIntegerField()),
                ('BasicInfo', models.CharField(max_length=200, verbose_name='详细资料')),
                ('DetailInfo', models.CharField(max_length=100, verbose_name='其他资料')),
                ('ObjectInfo', models.CharField(max_length=200, verbose_name='择偶标准')),
                ('vnums', models.SmallIntegerField()),
                ('showinfo', models.SmallIntegerField()),
                ('mate', models.CharField(max_length=100)),
                ('f_text', models.CharField(max_length=100, verbose_name='兴趣爱好')),
                ('pull_nums', models.SmallIntegerField()),
                ('imkey', models.SmallIntegerField()),
                ('revenue_type', models.SmallIntegerField()),
                ('ismeet', models.SmallIntegerField()),
                ('userlimit', models.SmallIntegerField()),
                ('basic', models.JSONField()),
                ('basicInfo2', models.CharField(max_length=100)),
                ('tag_true', models.CharField(max_length=100, verbose_name='理想中的TA')),
                ('thumb', models.CharField(max_length=100)),
                ('avatarURL', models.JSONField(verbose_name='头像')),
                ('giftCount', models.IntegerField(verbose_name='礼物数')),
                ('gift', models.CharField(max_length=100)),
                ('isFollowing', models.BooleanField()),
                ('userinfo', models.JSONField()),
                ('hn', models.CharField(max_length=100)),
                ('userinfocheck', models.JSONField()),
                ('client', models.IntegerField()),
                ('seo', models.JSONField()),
                ('isfull', models.BooleanField()),
                ('step', models.IntegerField()),
                ('memberID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'verbose_name': '会员详情',
                'verbose_name_plural': '会员详情',
            },
        ),
        migrations.CreateModel(
            name='UserProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/user_photo/', verbose_name='图片')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersprofile', to_field='memberID')),
            ],
            options={
                'verbose_name': '会员相册',
                'verbose_name_plural': '会员相册',
            },
        ),
    ]
