# Generated by Django 4.2.11 on 2026-05-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='ask_list',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='is_my_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='not_login_avatar_vague',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='show_ask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='show_tip_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='show_want',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='user_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='want_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
