# Generated by Django 4.2.10 on 2024-03-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='_id',
            new_name='user_id',
        ),
    ]
