# Generated by Django 4.2.10 on 2024-03-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename__id_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='user_id'),
        ),
    ]
