# Generated by Django 4.2.10 on 2024-03-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofilephoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilephoto',
            options={'verbose_name': '会员相册', 'verbose_name_plural': '会员相册'},
        ),
        migrations.RenameField(
            model_name='userprofilephoto',
            old_name='user',
            new_name='userprofile',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='用户ID'),
        ),
    ]
